# Generated by Django 3.2.3 on 2021-05-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210521_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
    ]
