# Generated by Django 3.2.3 on 2021-05-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='time',
            field=models.CharField(default='Some string', max_length=122),
        ),
    ]
