# Generated by Django 3.2.3 on 2021-05-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='user',
            field=models.CharField(max_length=64),
        ),
    ]
