# Generated by Django 3.2.3 on 2021-05-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_auction_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='bids',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='bids',
            name='item_name',
            field=models.CharField(default='some', max_length=64),
        ),
        migrations.AddField(
            model_name='bids',
            name='username',
            field=models.CharField(default='some', max_length=64, unique=True),
        ),
    ]
