# Generated by Django 3.2.3 on 2021-05-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210522_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='bids',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='bids',
            name='item_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='bids',
            name='username',
            field=models.CharField(max_length=64),
        ),
    ]
